name: Save Image To Repo

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'File name'
        required: true
      content:
        description: 'Base64 image content'
        required: true

jobs:
  save-image:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode Base64 and save file
        run: |
          mkdir -p captures
          echo "${{ github.event.inputs.content }}" | base64 --decode > captures/${{ github.event.inputs.filename }}

      - name: Commit and Push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "Repo Bot"
          git add captures/${{ github.event.inputs.filename }}
          git commit -m "Uploaded image ${{ github.event.inputs.filename }}" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_UPLOAD_TOKEN }}
